import json

with open('colab_run.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

cells = nb['cells']

step6_idx = -1
for i, c in enumerate(cells):
    if c['cell_type'] == 'markdown' and 'Step 6' in str(c.get('source', [])):
        step6_idx = i
        break

if step6_idx == -1:
    step6_idx = len(cells)

cells.insert(step6_idx, {'cell_type': 'markdown', 'metadata': {}, 'source': ['## Step 5D: 🤖 Train Transformer (DCT-ViT)\n', '*(Skip if using pretrained weights. Make sure to use GPU.)*']})
cells.insert(step6_idx+1, {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': ['!python train.py \\\n', '    --model transformer \\\n', '    --train_data $TRAIN_DATA \\\n', '    --test_data  $TEST_DATA \\\n', '    --batch_size 32 \\\n', '    --lr 1e-4 \\\n', '    --num_epoch 100']})
cells.insert(step6_idx+2, {'cell_type': 'markdown', 'metadata': {}, 'source': ['## Step 5E: 🤖 Test Transformer — Face Recognition\n']})
cells.insert(step6_idx+3, {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': ['# Replace logs/best.pth with the actual best checkpoints generated by Step 5D\n', '!python test_face_recognition.py \\\n', '    --model transformer \\\n', '    --test_data $TEST_DATA \\\n', '    --weights logs/best.pth \\\n', '    --batch_size 32']})
cells.insert(step6_idx+4, {'cell_type': 'markdown', 'metadata': {}, 'source': ['## Step 5F: 🤖 Test Transformer — Face Verification']})
cells.insert(step6_idx+5, {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': ['# Replace logs/best.pth with the actual best checkpoints generated by Step 5D\n', '!python test_face_verification.py \\\n', '    --model transformer \\\n', '    --test_data $TEST_DATA \\\n', '    --pairs data/verification_pairs.txt \\\n', '    --weights logs/best.pth\n']})

with open('colab_run.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=4)
